require:
  - rubocop-rake
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 3.1
  NewCops: enable

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes

Layout/LineLength:
  Max: 144

Layout/EndOfLine:
  Enabled: false

Lint/EmptyBlock:
  Enabled: false

Lint/UnusedMethodArgument:
  Enabled: false

Style/AsciiComments:
  Enabled: false

Style/EmptyMethod:
  Enabled: false
